# Generated by Django 5.1.2 on 2024-11-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0023_alter_complaint_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
