# Generated by Django 5.1.2 on 2024-11-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0024_complaint_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_details',
        ),
    ]
