# Generated by Django 5.1.2 on 2024-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0025_remove_complaint_complaint_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=6),
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
