# Generated by Django 5.1.2 on 2024-11-08 10:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0026_complaint_description_complaint_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
            ),
            preserve_default=False,
        ),
    ]