# Generated by Django 5.1.2 on 2024-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0028_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
        ),
    ]
