# Generated by Django 5.1.2 on 2024-11-08 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0030_alter_feedback_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={},
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comp_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='complaint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cc.complaint'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(),
        ),
    ]
